apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: products-app
type: Opaque
data:
  mysql-root-password: TXlTcWxSb290QDAwMQ==
  mysql-user: ZGJfdXNlcg==
  mysql-password: TXlTcWxSb290QDAwMQ==
  mysql-database: cHJvZHVjdHNfZGI=
  DB_URL: amRiYzpteXNxbDovL215c3FsLnByb2R1Y3RzLWFwcC5zdmMuY2x1c3Rlci5sb2NhbDozMzA2L3Byb2R1Y3RzX2RiP2VuYWJsZWRUTFNQcm90b2NvbHM9VExTdjEuMg==
  DB_USERNAME: ZGJfdXNlcg==
  DB_PASSWORD: TXlTcWxSb290QDAwMQ==
  DB_DRIVER: Y29tLm15c3FsLmNqLmpkYmMuRHJpdmVy
