apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: products-app
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS products_db;
    USE products_db;
    CREATE TABLE IF NOT EXISTS products (
        product_id INT PRIMARY KEY AUTO_INCREMENT,
        product_name VARCHAR(100),  
        product_description VARCHAR(255),
        price DECIMAL(10, 2)
    );
    CREATE TABLE IF NOT EXISTS test_products (
        product_id INT PRIMARY KEY AUTO_INCREMENT,
        product_name VARCHAR(100),
        product_description VARCHAR(255),
        price DECIMAL(10, 2)
    );